ci: test --no-project performance
Edit: didn't work

error: Failed to spawn: `mypy`
  Caused by: No such file or directory (os error 2)
Error: Process completed with exit code 2.