mypy tests (#1443)
* tests: fix mypy [no-untyped-def]

* tests: fix mypy [type-arg]

* tests: fix mypy [unreachable]

`if result is None: return None` got removed because
`store._store.get()` always returns a result / exception
and not an Optional. Even on the success (Result::Ok) scenario,
the only possibility in the Rust code is PyBytes.

* tests: fix mypy [no-untyped-call]

* tests: fix mypy [attr-defined]

* tests: fix mypy [arg-type]

* tests: fix mypy [union-attr]

* tests: fix mypy [misc]

* tests: fix mypy [return-value]

* tests: fix mypy [import-not-found]

* tests: fix mypy [call-arg]

* tests: fix mypy [dict-item]

* tests: fix mypy [unused-ignore]

* tests: fix mypy [no-untyped-call]

* tests: fix mypy [no-any-return]

* tests: fix mypy [override]

* tests: fix mypy [assignment]

* tests: fix mypy [index]

* ci: run mypy on tests folder too

* ruff format

* ci: test --no-project performance

Edit: didn't work

error: Failed to spawn: `mypy`
  Caused by: No such file or directory (os error 2)
Error: Process completed with exit code 2.

* ci: test --only-group dev performance

Didn't work as well (packages not found):

...
tests/run_xarray_backends_tests.py:15: error: Cannot find implementation or library stub for module named "zarr"  [import-not-found]
Found 129 errors in 36 files (checked 53 source files)

* ci: test --all-groups performance

As they say, third time is the charm.

* tests: ignore zarr type checking for older versions

* docs: add tests to mypy command